// Generated by auto imports
export {};
declare global {
  const GET_CLASSES: (typeof import("../../utils/queries"))["GET_CLASSES"];
  const GET_CONTACTS: (typeof import("../../utils/queries"))["GET_CONTACTS"];
  const GET_COURSE_CONTENTS: (typeof import("../../utils/queries"))["GET_COURSE_CONTENTS"];
  const GET_INSTRUCTORS: (typeof import("../../utils/queries"))["GET_INSTRUCTORS"];
  const GET_INTERVIEWS: (typeof import("../../utils/queries"))["GET_INTERVIEWS"];
  const GET_RANKINGS: (typeof import("../../utils/queries"))["GET_RANKINGS"];
  const GET_SYLLABUS: (typeof import("../../utils/queries"))["GET_SYLLABUS"];
  const abortNavigation: (typeof import("../../node_modules/nuxt/dist/app"))["abortNavigation"];
  const addRouteMiddleware: (typeof import("../../node_modules/nuxt/dist/app"))["addRouteMiddleware"];
  const blocksToText: (typeof import("../../composables/sanity-to-text"))["blocksToText"];
  const clearError: (typeof import("../../node_modules/nuxt/dist/app"))["clearError"];
  const clearNuxtData: (typeof import("../../node_modules/nuxt/dist/app"))["clearNuxtData"];
  const computed: (typeof import("vue"))["computed"];
  const createError: (typeof import("../../node_modules/nuxt/dist/app"))["createError"];
  const createInternalLinkResolver: (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["createInternalLinkResolver"];
  const createSanityClient: (typeof import("#build/sanity-client"))["createClient"];
  const customRef: (typeof import("vue"))["customRef"];
  const defineAddress: (typeof import("@unhead/schema-org-vue"))["defineAddress"];
  const defineAggregateOffer: (typeof import("@unhead/schema-org-vue"))["defineAggregateOffer"];
  const defineAggregateRating: (typeof import("@unhead/schema-org-vue"))["defineAggregateRating"];
  const defineAppConfig: (typeof import("../../node_modules/nuxt/dist/app"))["defineAppConfig"];
  const defineArticle: (typeof import("@unhead/schema-org-vue"))["defineArticle"];
  const defineAsyncComponent: (typeof import("vue"))["defineAsyncComponent"];
  const defineBook: (typeof import("@unhead/schema-org-vue"))["defineBook"];
  const defineBookEdition: (typeof import("@unhead/schema-org-vue"))["defineBookEdition"];
  const defineBreadcrumb: (typeof import("@unhead/schema-org-vue"))["defineBreadcrumb"];
  const defineComment: (typeof import("@unhead/schema-org-vue"))["defineComment"];
  const defineComponent: (typeof import("vue"))["defineComponent"];
  const defineCourse: (typeof import("@unhead/schema-org-vue"))["defineCourse"];
  const defineEvent: (typeof import("@unhead/schema-org-vue"))["defineEvent"];
  const defineHowTo: (typeof import("@unhead/schema-org-vue"))["defineHowTo"];
  const defineHowToStep: (typeof import("@unhead/schema-org-vue"))["defineHowToStep"];
  const defineImage: (typeof import("@unhead/schema-org-vue"))["defineImage"];
  const defineItemList: (typeof import("@unhead/schema-org-vue"))["defineItemList"];
  const defineJobPosting: (typeof import("@unhead/schema-org-vue"))["defineJobPosting"];
  const defineListItem: (typeof import("@unhead/schema-org-vue"))["defineListItem"];
  const defineLocalBusiness: (typeof import("@unhead/schema-org-vue"))["defineLocalBusiness"];
  const defineModel: (typeof import("vue"))["defineModel"];
  const defineMovie: (typeof import("@unhead/schema-org-vue"))["defineMovie"];
  const defineNuxtComponent: (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtComponent"];
  const defineNuxtLink: (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtLink"];
  const defineNuxtPlugin: (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtPlugin"];
  const defineNuxtRouteMiddleware: (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtRouteMiddleware"];
  const defineOffer: (typeof import("@unhead/schema-org-vue"))["defineOffer"];
  const defineOgImageDynamic: (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageDynamic"];
  const defineOgImageScreenshot: (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageScreenshot"];
  const defineOgImageStatic: (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageStatic"];
  const defineOpeningHours: (typeof import("@unhead/schema-org-vue"))["defineOpeningHours"];
  const defineOptions: (typeof import("vue"))["defineOptions"];
  const defineOrganization: (typeof import("@unhead/schema-org-vue"))["defineOrganization"];
  const definePageMeta: (typeof import("../../node_modules/nuxt/dist/pages/runtime/composables"))["definePageMeta"];
  const definePayloadPlugin: (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadPlugin"];
  const definePayloadReducer: (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadReducer"];
  const definePayloadReviver: (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadReviver"];
  const definePerson: (typeof import("@unhead/schema-org-vue"))["definePerson"];
  const definePlace: (typeof import("@unhead/schema-org-vue"))["definePlace"];
  const defineProduct: (typeof import("@unhead/schema-org-vue"))["defineProduct"];
  const defineQuestion: (typeof import("@unhead/schema-org-vue"))["defineQuestion"];
  const defineReadAction: (typeof import("@unhead/schema-org-vue"))["defineReadAction"];
  const defineRecipe: (typeof import("@unhead/schema-org-vue"))["defineRecipe"];
  const defineReview: (typeof import("@unhead/schema-org-vue"))["defineReview"];
  const defineRobotMeta: (typeof import("../../node_modules/nuxt-simple-robots/dist/runtime/composables/defineRobotMeta"))["defineRobotMeta"];
  const defineSearchAction: (typeof import("@unhead/schema-org-vue"))["defineSearchAction"];
  const defineSlots: (typeof import("vue"))["defineSlots"];
  const defineSoftwareApp: (typeof import("@unhead/schema-org-vue"))["defineSoftwareApp"];
  const defineVideo: (typeof import("@unhead/schema-org-vue"))["defineVideo"];
  const defineVirtualLocation: (typeof import("@unhead/schema-org-vue"))["defineVirtualLocation"];
  const defineWebPage: (typeof import("@unhead/schema-org-vue"))["defineWebPage"];
  const defineWebSite: (typeof import("@unhead/schema-org-vue"))["defineWebSite"];
  const effect: (typeof import("vue"))["effect"];
  const effectScope: (typeof import("vue"))["effectScope"];
  const generateId: (typeof import("../../composables/generateId"))["default"];
  const getCurrentInstance: (typeof import("vue"))["getCurrentInstance"];
  const getCurrentScope: (typeof import("vue"))["getCurrentScope"];
  const groq: (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/groq"))["groq"];
  const h: (typeof import("vue"))["h"];
  const hasInjectionContext: (typeof import("vue"))["hasInjectionContext"];
  const inject: (typeof import("vue"))["inject"];
  const injectHead: (typeof import("@unhead/vue"))["injectHead"];
  const isNuxtError: (typeof import("../../node_modules/nuxt/dist/app"))["isNuxtError"];
  const isPrerendered: (typeof import("../../node_modules/nuxt/dist/app"))["isPrerendered"];
  const isProxy: (typeof import("vue"))["isProxy"];
  const isReactive: (typeof import("vue"))["isReactive"];
  const isReadonly: (typeof import("vue"))["isReadonly"];
  const isRef: (typeof import("vue"))["isRef"];
  const isShallow: (typeof import("vue"))["isShallow"];
  const isVue2: (typeof import("../../node_modules/nuxt/dist/app/compat/vue-demi"))["isVue2"];
  const isVue3: (typeof import("../../node_modules/nuxt/dist/app/compat/vue-demi"))["isVue3"];
  const loadPayload: (typeof import("../../node_modules/nuxt/dist/app"))["loadPayload"];
  const markRaw: (typeof import("vue"))["markRaw"];
  const mergeModels: (typeof import("vue"))["mergeModels"];
  const navigateTo: (typeof import("../../node_modules/nuxt/dist/app"))["navigateTo"];
  const nextTick: (typeof import("vue"))["nextTick"];
  const onActivated: (typeof import("vue"))["onActivated"];
  const onBeforeMount: (typeof import("vue"))["onBeforeMount"];
  const onBeforeRouteLeave: (typeof import("../vue-router"))["onBeforeRouteLeave"];
  const onBeforeRouteUpdate: (typeof import("../vue-router"))["onBeforeRouteUpdate"];
  const onBeforeUnmount: (typeof import("vue"))["onBeforeUnmount"];
  const onBeforeUpdate: (typeof import("vue"))["onBeforeUpdate"];
  const onDeactivated: (typeof import("vue"))["onDeactivated"];
  const onErrorCaptured: (typeof import("vue"))["onErrorCaptured"];
  const onMounted: (typeof import("vue"))["onMounted"];
  const onNuxtReady: (typeof import("../../node_modules/nuxt/dist/app"))["onNuxtReady"];
  const onRenderTracked: (typeof import("vue"))["onRenderTracked"];
  const onRenderTriggered: (typeof import("vue"))["onRenderTriggered"];
  const onScopeDispose: (typeof import("vue"))["onScopeDispose"];
  const onServerPrefetch: (typeof import("vue"))["onServerPrefetch"];
  const onUnmounted: (typeof import("vue"))["onUnmounted"];
  const onUpdated: (typeof import("vue"))["onUpdated"];
  const prefetchComponents: (typeof import("../../node_modules/nuxt/dist/app"))["prefetchComponents"];
  const preloadComponents: (typeof import("../../node_modules/nuxt/dist/app"))["preloadComponents"];
  const preloadPayload: (typeof import("../../node_modules/nuxt/dist/app"))["preloadPayload"];
  const preloadRouteComponents: (typeof import("../../node_modules/nuxt/dist/app"))["preloadRouteComponents"];
  const provide: (typeof import("vue"))["provide"];
  const proxyRefs: (typeof import("vue"))["proxyRefs"];
  const reactive: (typeof import("vue"))["reactive"];
  const readonly: (typeof import("vue"))["readonly"];
  const ref: (typeof import("vue"))["ref"];
  const refreshNuxtData: (typeof import("../../node_modules/nuxt/dist/app"))["refreshNuxtData"];
  const reloadNuxtApp: (typeof import("../../node_modules/nuxt/dist/app"))["reloadNuxtApp"];
  const resolveAbsoluteInternalLink: (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["resolveAbsoluteInternalLink"];
  const resolveComponent: (typeof import("vue"))["resolveComponent"];
  const resolveTrailingSlash: (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["resolveTrailingSlash"];
  const routes: (typeof import("../../utils/routes"))["default"];
  const s2t_HTMLConvertHandler: (typeof import("../../composables/i18n"))["s2t_HTMLConvertHandler"];
  const serializers: (typeof import("../../utils/serializers"))["default"];
  const setPageLayout: (typeof import("../../node_modules/nuxt/dist/app"))["setPageLayout"];
  const setResponseStatus: (typeof import("../../node_modules/nuxt/dist/app"))["setResponseStatus"];
  const shallowReactive: (typeof import("vue"))["shallowReactive"];
  const shallowReadonly: (typeof import("vue"))["shallowReadonly"];
  const shallowRef: (typeof import("vue"))["shallowRef"];
  const showError: (typeof import("../../node_modules/nuxt/dist/app"))["showError"];
  const t2s_HTMLConvertHandler: (typeof import("../../composables/i18n"))["t2s_HTMLConvertHandler"];
  const titleCase: (typeof import("../../node_modules/nuxt-seo-kit/composables/casing"))["titleCase"];
  const toRaw: (typeof import("vue"))["toRaw"];
  const toRef: (typeof import("vue"))["toRef"];
  const toRefs: (typeof import("vue"))["toRefs"];
  const toValue: (typeof import("vue"))["toValue"];
  const triggerRef: (typeof import("vue"))["triggerRef"];
  const unref: (typeof import("vue"))["unref"];
  const updateAppConfig: (typeof import("../../node_modules/nuxt/dist/app"))["updateAppConfig"];
  const useAppConfig: (typeof import("../../node_modules/nuxt/dist/app"))["useAppConfig"];
  const useAsyncData: (typeof import("../../node_modules/nuxt/dist/app"))["useAsyncData"];
  const useAttrs: (typeof import("vue"))["useAttrs"];
  const useBreadcrumbs: (typeof import("../../node_modules/nuxt-seo-kit/composables/breacrumbs"))["useBreadcrumbs"];
  const useCookie: (typeof import("../../node_modules/nuxt/dist/app"))["useCookie"];
  const useCssModule: (typeof import("vue"))["useCssModule"];
  const useCssVars: (typeof import("vue"))["useCssVars"];
  const useDevice: (typeof import("../../node_modules/@nuxtjs/device/dist/runtime/composables/useDevice"))["default"];
  const useDeviceD: (typeof import("../../node_modules/@nuxtjs/device/dist/runtime/composables/useDevice.d"))["default"];
  const useError: (typeof import("../../node_modules/nuxt/dist/app"))["useError"];
  const useFetch: (typeof import("../../node_modules/nuxt/dist/app"))["useFetch"];
  const useGtag: (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useGtag"))["useGtag"];
  const useGtagConsent: (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useGtagConsent"))["useGtagConsent"];
  const useHead: (typeof import("@unhead/vue"))["useHead"];
  const useHeadSafe: (typeof import("@unhead/vue"))["useHeadSafe"];
  const useImage: (typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/composables"))["useImage"];
  const useLazyAsyncData: (typeof import("../../node_modules/nuxt/dist/app"))["useLazyAsyncData"];
  const useLazyFetch: (typeof import("../../node_modules/nuxt/dist/app"))["useLazyFetch"];
  const useLazySanityQuery: (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useLazySanityQuery"];
  const useLink: (typeof import("../vue-router"))["useLink"];
  const useModel: (typeof import("vue"))["useModel"];
  const useNuxtApp: (typeof import("../../node_modules/nuxt/dist/app"))["useNuxtApp"];
  const useNuxtData: (typeof import("../../node_modules/nuxt/dist/app"))["useNuxtData"];
  const useRequestEvent: (typeof import("../../node_modules/nuxt/dist/app"))["useRequestEvent"];
  const useRequestFetch: (typeof import("../../node_modules/nuxt/dist/app"))["useRequestFetch"];
  const useRequestHeaders: (typeof import("../../node_modules/nuxt/dist/app"))["useRequestHeaders"];
  const useRequestURL: (typeof import("../../node_modules/nuxt/dist/app"))["useRequestURL"];
  const useRoute: (typeof import("../../node_modules/nuxt/dist/app"))["useRoute"];
  const useRouter: (typeof import("../../node_modules/nuxt/dist/app"))["useRouter"];
  const useRuntimeConfig: (typeof import("../../node_modules/nuxt/dist/app"))["useRuntimeConfig"];
  const useSanity: (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useSanity"];
  const useSanityQuery: (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useSanityQuery"];
  const useSchemaOrg: (typeof import("@unhead/schema-org-vue"))["useSchemaOrg"];
  const useSeoMeta: (typeof import("@unhead/vue"))["useSeoMeta"];
  const useServerHead: (typeof import("@unhead/vue"))["useServerHead"];
  const useServerHeadSafe: (typeof import("@unhead/vue"))["useServerHeadSafe"];
  const useServerSeoMeta: (typeof import("@unhead/vue"))["useServerSeoMeta"];
  const useSlots: (typeof import("vue"))["useSlots"];
  const useState: (typeof import("../../node_modules/nuxt/dist/app"))["useState"];
  const useTrackEvent: (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useTrackEvent"))["useTrackEvent"];
  const useTransitionState: (typeof import("vue"))["useTransitionState"];
  const watch: (typeof import("vue"))["watch"];
  const watchEffect: (typeof import("vue"))["watchEffect"];
  const watchPostEffect: (typeof import("vue"))["watchPostEffect"];
  const watchSyncEffect: (typeof import("vue"))["watchSyncEffect"];
  const withCtx: (typeof import("vue"))["withCtx"];
  const withDirectives: (typeof import("vue"))["withDirectives"];
  const withKeys: (typeof import("vue"))["withKeys"];
  const withMemo: (typeof import("vue"))["withMemo"];
  const withModifiers: (typeof import("vue"))["withModifiers"];
  const withScopeId: (typeof import("vue"))["withScopeId"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    ComponentPublicInstance,
    ComputedRef,
    InjectionKey,
    PropType,
    Ref,
    VNode,
  } from "vue";
}
// for vue template auto import
import { UnwrapRef } from "vue";
declare module "vue" {
  interface ComponentCustomProperties {
    readonly GET_CLASSES: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_CLASSES"]
    >;
    readonly GET_CONTACTS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_CONTACTS"]
    >;
    readonly GET_COURSE_CONTENTS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_COURSE_CONTENTS"]
    >;
    readonly GET_INSTRUCTORS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_INSTRUCTORS"]
    >;
    readonly GET_INTERVIEWS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_INTERVIEWS"]
    >;
    readonly GET_RANKINGS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_RANKINGS"]
    >;
    readonly GET_SYLLABUS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_SYLLABUS"]
    >;
    readonly abortNavigation: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["abortNavigation"]
    >;
    readonly addRouteMiddleware: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["addRouteMiddleware"]
    >;
    readonly blocksToText: UnwrapRef<
      (typeof import("../../composables/sanity-to-text"))["blocksToText"]
    >;
    readonly clearError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["clearError"]
    >;
    readonly clearNuxtData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["clearNuxtData"]
    >;
    readonly computed: UnwrapRef<(typeof import("vue"))["computed"]>;
    readonly createError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["createError"]
    >;
    readonly createInternalLinkResolver: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["createInternalLinkResolver"]
    >;
    readonly createSanityClient: UnwrapRef<
      (typeof import("#build/sanity-client"))["createClient"]
    >;
    readonly customRef: UnwrapRef<(typeof import("vue"))["customRef"]>;
    readonly defineAddress: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineAddress"]
    >;
    readonly defineAggregateOffer: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineAggregateOffer"]
    >;
    readonly defineAggregateRating: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineAggregateRating"]
    >;
    readonly defineAppConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineAppConfig"]
    >;
    readonly defineArticle: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineArticle"]
    >;
    readonly defineAsyncComponent: UnwrapRef<
      (typeof import("vue"))["defineAsyncComponent"]
    >;
    readonly defineBook: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineBook"]
    >;
    readonly defineBookEdition: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineBookEdition"]
    >;
    readonly defineBreadcrumb: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineBreadcrumb"]
    >;
    readonly defineComment: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineComment"]
    >;
    readonly defineComponent: UnwrapRef<
      (typeof import("vue"))["defineComponent"]
    >;
    readonly defineCourse: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineCourse"]
    >;
    readonly defineEvent: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineEvent"]
    >;
    readonly defineHowTo: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineHowTo"]
    >;
    readonly defineHowToStep: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineHowToStep"]
    >;
    readonly defineImage: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineImage"]
    >;
    readonly defineItemList: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineItemList"]
    >;
    readonly defineJobPosting: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineJobPosting"]
    >;
    readonly defineListItem: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineListItem"]
    >;
    readonly defineLocalBusiness: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineLocalBusiness"]
    >;
    readonly defineModel: UnwrapRef<(typeof import("vue"))["defineModel"]>;
    readonly defineMovie: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineMovie"]
    >;
    readonly defineNuxtComponent: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtComponent"]
    >;
    readonly defineNuxtLink: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtLink"]
    >;
    readonly defineNuxtPlugin: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtPlugin"]
    >;
    readonly defineNuxtRouteMiddleware: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtRouteMiddleware"]
    >;
    readonly defineOffer: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineOffer"]
    >;
    readonly defineOgImageDynamic: UnwrapRef<
      (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageDynamic"]
    >;
    readonly defineOgImageScreenshot: UnwrapRef<
      (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageScreenshot"]
    >;
    readonly defineOgImageStatic: UnwrapRef<
      (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageStatic"]
    >;
    readonly defineOpeningHours: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineOpeningHours"]
    >;
    readonly defineOptions: UnwrapRef<(typeof import("vue"))["defineOptions"]>;
    readonly defineOrganization: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineOrganization"]
    >;
    readonly definePageMeta: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/pages/runtime/composables"))["definePageMeta"]
    >;
    readonly definePayloadPlugin: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadPlugin"]
    >;
    readonly definePayloadReducer: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadReducer"]
    >;
    readonly definePayloadReviver: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadReviver"]
    >;
    readonly definePerson: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["definePerson"]
    >;
    readonly definePlace: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["definePlace"]
    >;
    readonly defineProduct: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineProduct"]
    >;
    readonly defineQuestion: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineQuestion"]
    >;
    readonly defineReadAction: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineReadAction"]
    >;
    readonly defineRecipe: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineRecipe"]
    >;
    readonly defineReview: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineReview"]
    >;
    readonly defineRobotMeta: UnwrapRef<
      (typeof import("../../node_modules/nuxt-simple-robots/dist/runtime/composables/defineRobotMeta"))["defineRobotMeta"]
    >;
    readonly defineSearchAction: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineSearchAction"]
    >;
    readonly defineSlots: UnwrapRef<(typeof import("vue"))["defineSlots"]>;
    readonly defineSoftwareApp: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineSoftwareApp"]
    >;
    readonly defineVideo: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineVideo"]
    >;
    readonly defineVirtualLocation: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineVirtualLocation"]
    >;
    readonly defineWebPage: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineWebPage"]
    >;
    readonly defineWebSite: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineWebSite"]
    >;
    readonly effect: UnwrapRef<(typeof import("vue"))["effect"]>;
    readonly effectScope: UnwrapRef<(typeof import("vue"))["effectScope"]>;
    readonly generateId: UnwrapRef<
      (typeof import("../../composables/generateId"))["default"]
    >;
    readonly getCurrentInstance: UnwrapRef<
      (typeof import("vue"))["getCurrentInstance"]
    >;
    readonly getCurrentScope: UnwrapRef<
      (typeof import("vue"))["getCurrentScope"]
    >;
    readonly groq: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/groq"))["groq"]
    >;
    readonly h: UnwrapRef<(typeof import("vue"))["h"]>;
    readonly hasInjectionContext: UnwrapRef<
      (typeof import("vue"))["hasInjectionContext"]
    >;
    readonly inject: UnwrapRef<(typeof import("vue"))["inject"]>;
    readonly injectHead: UnwrapRef<
      (typeof import("@unhead/vue"))["injectHead"]
    >;
    readonly isNuxtError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["isNuxtError"]
    >;
    readonly isPrerendered: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["isPrerendered"]
    >;
    readonly isProxy: UnwrapRef<(typeof import("vue"))["isProxy"]>;
    readonly isReactive: UnwrapRef<(typeof import("vue"))["isReactive"]>;
    readonly isReadonly: UnwrapRef<(typeof import("vue"))["isReadonly"]>;
    readonly isRef: UnwrapRef<(typeof import("vue"))["isRef"]>;
    readonly isShallow: UnwrapRef<(typeof import("vue"))["isShallow"]>;
    readonly isVue2: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app/compat/vue-demi"))["isVue2"]
    >;
    readonly isVue3: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app/compat/vue-demi"))["isVue3"]
    >;
    readonly loadPayload: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["loadPayload"]
    >;
    readonly markRaw: UnwrapRef<(typeof import("vue"))["markRaw"]>;
    readonly mergeModels: UnwrapRef<(typeof import("vue"))["mergeModels"]>;
    readonly navigateTo: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["navigateTo"]
    >;
    readonly nextTick: UnwrapRef<(typeof import("vue"))["nextTick"]>;
    readonly onActivated: UnwrapRef<(typeof import("vue"))["onActivated"]>;
    readonly onBeforeMount: UnwrapRef<(typeof import("vue"))["onBeforeMount"]>;
    readonly onBeforeRouteLeave: UnwrapRef<
      (typeof import("../vue-router"))["onBeforeRouteLeave"]
    >;
    readonly onBeforeRouteUpdate: UnwrapRef<
      (typeof import("../vue-router"))["onBeforeRouteUpdate"]
    >;
    readonly onBeforeUnmount: UnwrapRef<
      (typeof import("vue"))["onBeforeUnmount"]
    >;
    readonly onBeforeUpdate: UnwrapRef<
      (typeof import("vue"))["onBeforeUpdate"]
    >;
    readonly onDeactivated: UnwrapRef<(typeof import("vue"))["onDeactivated"]>;
    readonly onErrorCaptured: UnwrapRef<
      (typeof import("vue"))["onErrorCaptured"]
    >;
    readonly onMounted: UnwrapRef<(typeof import("vue"))["onMounted"]>;
    readonly onNuxtReady: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["onNuxtReady"]
    >;
    readonly onRenderTracked: UnwrapRef<
      (typeof import("vue"))["onRenderTracked"]
    >;
    readonly onRenderTriggered: UnwrapRef<
      (typeof import("vue"))["onRenderTriggered"]
    >;
    readonly onScopeDispose: UnwrapRef<
      (typeof import("vue"))["onScopeDispose"]
    >;
    readonly onServerPrefetch: UnwrapRef<
      (typeof import("vue"))["onServerPrefetch"]
    >;
    readonly onUnmounted: UnwrapRef<(typeof import("vue"))["onUnmounted"]>;
    readonly onUpdated: UnwrapRef<(typeof import("vue"))["onUpdated"]>;
    readonly prefetchComponents: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["prefetchComponents"]
    >;
    readonly preloadComponents: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["preloadComponents"]
    >;
    readonly preloadPayload: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["preloadPayload"]
    >;
    readonly preloadRouteComponents: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["preloadRouteComponents"]
    >;
    readonly provide: UnwrapRef<(typeof import("vue"))["provide"]>;
    readonly proxyRefs: UnwrapRef<(typeof import("vue"))["proxyRefs"]>;
    readonly reactive: UnwrapRef<(typeof import("vue"))["reactive"]>;
    readonly readonly: UnwrapRef<(typeof import("vue"))["readonly"]>;
    readonly ref: UnwrapRef<(typeof import("vue"))["ref"]>;
    readonly refreshNuxtData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["refreshNuxtData"]
    >;
    readonly reloadNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["reloadNuxtApp"]
    >;
    readonly resolveAbsoluteInternalLink: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["resolveAbsoluteInternalLink"]
    >;
    readonly resolveComponent: UnwrapRef<
      (typeof import("vue"))["resolveComponent"]
    >;
    readonly resolveTrailingSlash: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["resolveTrailingSlash"]
    >;
    readonly routes: UnwrapRef<
      (typeof import("../../utils/routes"))["default"]
    >;
    readonly s2t_HTMLConvertHandler: UnwrapRef<
      (typeof import("../../composables/i18n"))["s2t_HTMLConvertHandler"]
    >;
    readonly serializers: UnwrapRef<
      (typeof import("../../utils/serializers"))["default"]
    >;
    readonly setPageLayout: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["setPageLayout"]
    >;
    readonly setResponseStatus: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["setResponseStatus"]
    >;
    readonly shallowReactive: UnwrapRef<
      (typeof import("vue"))["shallowReactive"]
    >;
    readonly shallowReadonly: UnwrapRef<
      (typeof import("vue"))["shallowReadonly"]
    >;
    readonly shallowRef: UnwrapRef<(typeof import("vue"))["shallowRef"]>;
    readonly showError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["showError"]
    >;
    readonly t2s_HTMLConvertHandler: UnwrapRef<
      (typeof import("../../composables/i18n"))["t2s_HTMLConvertHandler"]
    >;
    readonly titleCase: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/casing"))["titleCase"]
    >;
    readonly toRaw: UnwrapRef<(typeof import("vue"))["toRaw"]>;
    readonly toRef: UnwrapRef<(typeof import("vue"))["toRef"]>;
    readonly toRefs: UnwrapRef<(typeof import("vue"))["toRefs"]>;
    readonly toValue: UnwrapRef<(typeof import("vue"))["toValue"]>;
    readonly triggerRef: UnwrapRef<(typeof import("vue"))["triggerRef"]>;
    readonly unref: UnwrapRef<(typeof import("vue"))["unref"]>;
    readonly updateAppConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["updateAppConfig"]
    >;
    readonly useAppConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useAppConfig"]
    >;
    readonly useAsyncData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useAsyncData"]
    >;
    readonly useAttrs: UnwrapRef<(typeof import("vue"))["useAttrs"]>;
    readonly useBreadcrumbs: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/breacrumbs"))["useBreadcrumbs"]
    >;
    readonly useCookie: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useCookie"]
    >;
    readonly useCssModule: UnwrapRef<(typeof import("vue"))["useCssModule"]>;
    readonly useCssVars: UnwrapRef<(typeof import("vue"))["useCssVars"]>;
    readonly useDevice: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/device/dist/runtime/composables/useDevice"))["default"]
    >;
    readonly useDeviceD: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/device/dist/runtime/composables/useDevice.d"))["default"]
    >;
    readonly useError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useError"]
    >;
    readonly useFetch: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useFetch"]
    >;
    readonly useGtag: UnwrapRef<
      (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useGtag"))["useGtag"]
    >;
    readonly useGtagConsent: UnwrapRef<
      (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useGtagConsent"))["useGtagConsent"]
    >;
    readonly useHead: UnwrapRef<(typeof import("@unhead/vue"))["useHead"]>;
    readonly useHeadSafe: UnwrapRef<
      (typeof import("@unhead/vue"))["useHeadSafe"]
    >;
    readonly useImage: UnwrapRef<
      (typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/composables"))["useImage"]
    >;
    readonly useLazyAsyncData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useLazyAsyncData"]
    >;
    readonly useLazyFetch: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useLazyFetch"]
    >;
    readonly useLazySanityQuery: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useLazySanityQuery"]
    >;
    readonly useLink: UnwrapRef<(typeof import("../vue-router"))["useLink"]>;
    readonly useModel: UnwrapRef<(typeof import("vue"))["useModel"]>;
    readonly useNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useNuxtApp"]
    >;
    readonly useNuxtData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useNuxtData"]
    >;
    readonly useRequestEvent: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestEvent"]
    >;
    readonly useRequestFetch: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestFetch"]
    >;
    readonly useRequestHeaders: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestHeaders"]
    >;
    readonly useRequestURL: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestURL"]
    >;
    readonly useRoute: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRoute"]
    >;
    readonly useRouter: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRouter"]
    >;
    readonly useRuntimeConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRuntimeConfig"]
    >;
    readonly useSanity: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useSanity"]
    >;
    readonly useSanityQuery: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useSanityQuery"]
    >;
    readonly useSchemaOrg: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["useSchemaOrg"]
    >;
    readonly useSeoMeta: UnwrapRef<
      (typeof import("@unhead/vue"))["useSeoMeta"]
    >;
    readonly useServerHead: UnwrapRef<
      (typeof import("@unhead/vue"))["useServerHead"]
    >;
    readonly useServerHeadSafe: UnwrapRef<
      (typeof import("@unhead/vue"))["useServerHeadSafe"]
    >;
    readonly useServerSeoMeta: UnwrapRef<
      (typeof import("@unhead/vue"))["useServerSeoMeta"]
    >;
    readonly useSlots: UnwrapRef<(typeof import("vue"))["useSlots"]>;
    readonly useState: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useState"]
    >;
    readonly useTrackEvent: UnwrapRef<
      (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useTrackEvent"))["useTrackEvent"]
    >;
    readonly useTransitionState: UnwrapRef<
      (typeof import("vue"))["useTransitionState"]
    >;
    readonly watch: UnwrapRef<(typeof import("vue"))["watch"]>;
    readonly watchEffect: UnwrapRef<(typeof import("vue"))["watchEffect"]>;
    readonly watchPostEffect: UnwrapRef<
      (typeof import("vue"))["watchPostEffect"]
    >;
    readonly watchSyncEffect: UnwrapRef<
      (typeof import("vue"))["watchSyncEffect"]
    >;
    readonly withCtx: UnwrapRef<(typeof import("vue"))["withCtx"]>;
    readonly withDirectives: UnwrapRef<
      (typeof import("vue"))["withDirectives"]
    >;
    readonly withKeys: UnwrapRef<(typeof import("vue"))["withKeys"]>;
    readonly withMemo: UnwrapRef<(typeof import("vue"))["withMemo"]>;
    readonly withModifiers: UnwrapRef<(typeof import("vue"))["withModifiers"]>;
    readonly withScopeId: UnwrapRef<(typeof import("vue"))["withScopeId"]>;
  }
}
declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    readonly GET_CLASSES: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_CLASSES"]
    >;
    readonly GET_CONTACTS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_CONTACTS"]
    >;
    readonly GET_COURSE_CONTENTS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_COURSE_CONTENTS"]
    >;
    readonly GET_INSTRUCTORS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_INSTRUCTORS"]
    >;
    readonly GET_INTERVIEWS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_INTERVIEWS"]
    >;
    readonly GET_RANKINGS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_RANKINGS"]
    >;
    readonly GET_SYLLABUS: UnwrapRef<
      (typeof import("../../utils/queries"))["GET_SYLLABUS"]
    >;
    readonly abortNavigation: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["abortNavigation"]
    >;
    readonly addRouteMiddleware: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["addRouteMiddleware"]
    >;
    readonly blocksToText: UnwrapRef<
      (typeof import("../../composables/sanity-to-text"))["blocksToText"]
    >;
    readonly clearError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["clearError"]
    >;
    readonly clearNuxtData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["clearNuxtData"]
    >;
    readonly computed: UnwrapRef<(typeof import("vue"))["computed"]>;
    readonly createError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["createError"]
    >;
    readonly createInternalLinkResolver: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["createInternalLinkResolver"]
    >;
    readonly createSanityClient: UnwrapRef<
      (typeof import("#build/sanity-client"))["createClient"]
    >;
    readonly customRef: UnwrapRef<(typeof import("vue"))["customRef"]>;
    readonly defineAddress: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineAddress"]
    >;
    readonly defineAggregateOffer: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineAggregateOffer"]
    >;
    readonly defineAggregateRating: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineAggregateRating"]
    >;
    readonly defineAppConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineAppConfig"]
    >;
    readonly defineArticle: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineArticle"]
    >;
    readonly defineAsyncComponent: UnwrapRef<
      (typeof import("vue"))["defineAsyncComponent"]
    >;
    readonly defineBook: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineBook"]
    >;
    readonly defineBookEdition: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineBookEdition"]
    >;
    readonly defineBreadcrumb: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineBreadcrumb"]
    >;
    readonly defineComment: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineComment"]
    >;
    readonly defineComponent: UnwrapRef<
      (typeof import("vue"))["defineComponent"]
    >;
    readonly defineCourse: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineCourse"]
    >;
    readonly defineEvent: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineEvent"]
    >;
    readonly defineHowTo: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineHowTo"]
    >;
    readonly defineHowToStep: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineHowToStep"]
    >;
    readonly defineImage: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineImage"]
    >;
    readonly defineItemList: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineItemList"]
    >;
    readonly defineJobPosting: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineJobPosting"]
    >;
    readonly defineListItem: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineListItem"]
    >;
    readonly defineLocalBusiness: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineLocalBusiness"]
    >;
    readonly defineModel: UnwrapRef<(typeof import("vue"))["defineModel"]>;
    readonly defineMovie: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineMovie"]
    >;
    readonly defineNuxtComponent: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtComponent"]
    >;
    readonly defineNuxtLink: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtLink"]
    >;
    readonly defineNuxtPlugin: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtPlugin"]
    >;
    readonly defineNuxtRouteMiddleware: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["defineNuxtRouteMiddleware"]
    >;
    readonly defineOffer: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineOffer"]
    >;
    readonly defineOgImageDynamic: UnwrapRef<
      (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageDynamic"]
    >;
    readonly defineOgImageScreenshot: UnwrapRef<
      (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageScreenshot"]
    >;
    readonly defineOgImageStatic: UnwrapRef<
      (typeof import("../../node_modules/nuxt-og-image/dist/runtime/composables/defineOgImage"))["defineOgImageStatic"]
    >;
    readonly defineOpeningHours: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineOpeningHours"]
    >;
    readonly defineOptions: UnwrapRef<(typeof import("vue"))["defineOptions"]>;
    readonly defineOrganization: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineOrganization"]
    >;
    readonly definePageMeta: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/pages/runtime/composables"))["definePageMeta"]
    >;
    readonly definePayloadPlugin: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadPlugin"]
    >;
    readonly definePayloadReducer: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadReducer"]
    >;
    readonly definePayloadReviver: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["definePayloadReviver"]
    >;
    readonly definePerson: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["definePerson"]
    >;
    readonly definePlace: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["definePlace"]
    >;
    readonly defineProduct: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineProduct"]
    >;
    readonly defineQuestion: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineQuestion"]
    >;
    readonly defineReadAction: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineReadAction"]
    >;
    readonly defineRecipe: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineRecipe"]
    >;
    readonly defineReview: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineReview"]
    >;
    readonly defineRobotMeta: UnwrapRef<
      (typeof import("../../node_modules/nuxt-simple-robots/dist/runtime/composables/defineRobotMeta"))["defineRobotMeta"]
    >;
    readonly defineSearchAction: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineSearchAction"]
    >;
    readonly defineSlots: UnwrapRef<(typeof import("vue"))["defineSlots"]>;
    readonly defineSoftwareApp: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineSoftwareApp"]
    >;
    readonly defineVideo: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineVideo"]
    >;
    readonly defineVirtualLocation: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineVirtualLocation"]
    >;
    readonly defineWebPage: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineWebPage"]
    >;
    readonly defineWebSite: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["defineWebSite"]
    >;
    readonly effect: UnwrapRef<(typeof import("vue"))["effect"]>;
    readonly effectScope: UnwrapRef<(typeof import("vue"))["effectScope"]>;
    readonly generateId: UnwrapRef<
      (typeof import("../../composables/generateId"))["default"]
    >;
    readonly getCurrentInstance: UnwrapRef<
      (typeof import("vue"))["getCurrentInstance"]
    >;
    readonly getCurrentScope: UnwrapRef<
      (typeof import("vue"))["getCurrentScope"]
    >;
    readonly groq: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/groq"))["groq"]
    >;
    readonly h: UnwrapRef<(typeof import("vue"))["h"]>;
    readonly hasInjectionContext: UnwrapRef<
      (typeof import("vue"))["hasInjectionContext"]
    >;
    readonly inject: UnwrapRef<(typeof import("vue"))["inject"]>;
    readonly injectHead: UnwrapRef<
      (typeof import("@unhead/vue"))["injectHead"]
    >;
    readonly isNuxtError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["isNuxtError"]
    >;
    readonly isPrerendered: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["isPrerendered"]
    >;
    readonly isProxy: UnwrapRef<(typeof import("vue"))["isProxy"]>;
    readonly isReactive: UnwrapRef<(typeof import("vue"))["isReactive"]>;
    readonly isReadonly: UnwrapRef<(typeof import("vue"))["isReadonly"]>;
    readonly isRef: UnwrapRef<(typeof import("vue"))["isRef"]>;
    readonly isShallow: UnwrapRef<(typeof import("vue"))["isShallow"]>;
    readonly isVue2: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app/compat/vue-demi"))["isVue2"]
    >;
    readonly isVue3: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app/compat/vue-demi"))["isVue3"]
    >;
    readonly loadPayload: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["loadPayload"]
    >;
    readonly markRaw: UnwrapRef<(typeof import("vue"))["markRaw"]>;
    readonly mergeModels: UnwrapRef<(typeof import("vue"))["mergeModels"]>;
    readonly navigateTo: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["navigateTo"]
    >;
    readonly nextTick: UnwrapRef<(typeof import("vue"))["nextTick"]>;
    readonly onActivated: UnwrapRef<(typeof import("vue"))["onActivated"]>;
    readonly onBeforeMount: UnwrapRef<(typeof import("vue"))["onBeforeMount"]>;
    readonly onBeforeRouteLeave: UnwrapRef<
      (typeof import("../vue-router"))["onBeforeRouteLeave"]
    >;
    readonly onBeforeRouteUpdate: UnwrapRef<
      (typeof import("../vue-router"))["onBeforeRouteUpdate"]
    >;
    readonly onBeforeUnmount: UnwrapRef<
      (typeof import("vue"))["onBeforeUnmount"]
    >;
    readonly onBeforeUpdate: UnwrapRef<
      (typeof import("vue"))["onBeforeUpdate"]
    >;
    readonly onDeactivated: UnwrapRef<(typeof import("vue"))["onDeactivated"]>;
    readonly onErrorCaptured: UnwrapRef<
      (typeof import("vue"))["onErrorCaptured"]
    >;
    readonly onMounted: UnwrapRef<(typeof import("vue"))["onMounted"]>;
    readonly onNuxtReady: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["onNuxtReady"]
    >;
    readonly onRenderTracked: UnwrapRef<
      (typeof import("vue"))["onRenderTracked"]
    >;
    readonly onRenderTriggered: UnwrapRef<
      (typeof import("vue"))["onRenderTriggered"]
    >;
    readonly onScopeDispose: UnwrapRef<
      (typeof import("vue"))["onScopeDispose"]
    >;
    readonly onServerPrefetch: UnwrapRef<
      (typeof import("vue"))["onServerPrefetch"]
    >;
    readonly onUnmounted: UnwrapRef<(typeof import("vue"))["onUnmounted"]>;
    readonly onUpdated: UnwrapRef<(typeof import("vue"))["onUpdated"]>;
    readonly prefetchComponents: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["prefetchComponents"]
    >;
    readonly preloadComponents: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["preloadComponents"]
    >;
    readonly preloadPayload: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["preloadPayload"]
    >;
    readonly preloadRouteComponents: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["preloadRouteComponents"]
    >;
    readonly provide: UnwrapRef<(typeof import("vue"))["provide"]>;
    readonly proxyRefs: UnwrapRef<(typeof import("vue"))["proxyRefs"]>;
    readonly reactive: UnwrapRef<(typeof import("vue"))["reactive"]>;
    readonly readonly: UnwrapRef<(typeof import("vue"))["readonly"]>;
    readonly ref: UnwrapRef<(typeof import("vue"))["ref"]>;
    readonly refreshNuxtData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["refreshNuxtData"]
    >;
    readonly reloadNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["reloadNuxtApp"]
    >;
    readonly resolveAbsoluteInternalLink: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["resolveAbsoluteInternalLink"]
    >;
    readonly resolveComponent: UnwrapRef<
      (typeof import("vue"))["resolveComponent"]
    >;
    readonly resolveTrailingSlash: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/internalLinks"))["resolveTrailingSlash"]
    >;
    readonly routes: UnwrapRef<
      (typeof import("../../utils/routes"))["default"]
    >;
    readonly s2t_HTMLConvertHandler: UnwrapRef<
      (typeof import("../../composables/i18n"))["s2t_HTMLConvertHandler"]
    >;
    readonly serializers: UnwrapRef<
      (typeof import("../../utils/serializers"))["default"]
    >;
    readonly setPageLayout: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["setPageLayout"]
    >;
    readonly setResponseStatus: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["setResponseStatus"]
    >;
    readonly shallowReactive: UnwrapRef<
      (typeof import("vue"))["shallowReactive"]
    >;
    readonly shallowReadonly: UnwrapRef<
      (typeof import("vue"))["shallowReadonly"]
    >;
    readonly shallowRef: UnwrapRef<(typeof import("vue"))["shallowRef"]>;
    readonly showError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["showError"]
    >;
    readonly t2s_HTMLConvertHandler: UnwrapRef<
      (typeof import("../../composables/i18n"))["t2s_HTMLConvertHandler"]
    >;
    readonly titleCase: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/casing"))["titleCase"]
    >;
    readonly toRaw: UnwrapRef<(typeof import("vue"))["toRaw"]>;
    readonly toRef: UnwrapRef<(typeof import("vue"))["toRef"]>;
    readonly toRefs: UnwrapRef<(typeof import("vue"))["toRefs"]>;
    readonly toValue: UnwrapRef<(typeof import("vue"))["toValue"]>;
    readonly triggerRef: UnwrapRef<(typeof import("vue"))["triggerRef"]>;
    readonly unref: UnwrapRef<(typeof import("vue"))["unref"]>;
    readonly updateAppConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["updateAppConfig"]
    >;
    readonly useAppConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useAppConfig"]
    >;
    readonly useAsyncData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useAsyncData"]
    >;
    readonly useAttrs: UnwrapRef<(typeof import("vue"))["useAttrs"]>;
    readonly useBreadcrumbs: UnwrapRef<
      (typeof import("../../node_modules/nuxt-seo-kit/composables/breacrumbs"))["useBreadcrumbs"]
    >;
    readonly useCookie: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useCookie"]
    >;
    readonly useCssModule: UnwrapRef<(typeof import("vue"))["useCssModule"]>;
    readonly useCssVars: UnwrapRef<(typeof import("vue"))["useCssVars"]>;
    readonly useDevice: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/device/dist/runtime/composables/useDevice"))["default"]
    >;
    readonly useDeviceD: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/device/dist/runtime/composables/useDevice.d"))["default"]
    >;
    readonly useError: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useError"]
    >;
    readonly useFetch: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useFetch"]
    >;
    readonly useGtag: UnwrapRef<
      (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useGtag"))["useGtag"]
    >;
    readonly useGtagConsent: UnwrapRef<
      (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useGtagConsent"))["useGtagConsent"]
    >;
    readonly useHead: UnwrapRef<(typeof import("@unhead/vue"))["useHead"]>;
    readonly useHeadSafe: UnwrapRef<
      (typeof import("@unhead/vue"))["useHeadSafe"]
    >;
    readonly useImage: UnwrapRef<
      (typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/composables"))["useImage"]
    >;
    readonly useLazyAsyncData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useLazyAsyncData"]
    >;
    readonly useLazyFetch: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useLazyFetch"]
    >;
    readonly useLazySanityQuery: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useLazySanityQuery"]
    >;
    readonly useLink: UnwrapRef<(typeof import("../vue-router"))["useLink"]>;
    readonly useModel: UnwrapRef<(typeof import("vue"))["useModel"]>;
    readonly useNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useNuxtApp"]
    >;
    readonly useNuxtData: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useNuxtData"]
    >;
    readonly useRequestEvent: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestEvent"]
    >;
    readonly useRequestFetch: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestFetch"]
    >;
    readonly useRequestHeaders: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestHeaders"]
    >;
    readonly useRequestURL: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRequestURL"]
    >;
    readonly useRoute: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRoute"]
    >;
    readonly useRouter: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRouter"]
    >;
    readonly useRuntimeConfig: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useRuntimeConfig"]
    >;
    readonly useSanity: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useSanity"]
    >;
    readonly useSanityQuery: UnwrapRef<
      (typeof import("../../node_modules/@nuxtjs/sanity/dist/runtime/composables"))["useSanityQuery"]
    >;
    readonly useSchemaOrg: UnwrapRef<
      (typeof import("@unhead/schema-org-vue"))["useSchemaOrg"]
    >;
    readonly useSeoMeta: UnwrapRef<
      (typeof import("@unhead/vue"))["useSeoMeta"]
    >;
    readonly useServerHead: UnwrapRef<
      (typeof import("@unhead/vue"))["useServerHead"]
    >;
    readonly useServerHeadSafe: UnwrapRef<
      (typeof import("@unhead/vue"))["useServerHeadSafe"]
    >;
    readonly useServerSeoMeta: UnwrapRef<
      (typeof import("@unhead/vue"))["useServerSeoMeta"]
    >;
    readonly useSlots: UnwrapRef<(typeof import("vue"))["useSlots"]>;
    readonly useState: UnwrapRef<
      (typeof import("../../node_modules/nuxt/dist/app"))["useState"]
    >;
    readonly useTrackEvent: UnwrapRef<
      (typeof import("../../node_modules/nuxt-gtag/dist/runtime/composables/useTrackEvent"))["useTrackEvent"]
    >;
    readonly useTransitionState: UnwrapRef<
      (typeof import("vue"))["useTransitionState"]
    >;
    readonly watch: UnwrapRef<(typeof import("vue"))["watch"]>;
    readonly watchEffect: UnwrapRef<(typeof import("vue"))["watchEffect"]>;
    readonly watchPostEffect: UnwrapRef<
      (typeof import("vue"))["watchPostEffect"]
    >;
    readonly watchSyncEffect: UnwrapRef<
      (typeof import("vue"))["watchSyncEffect"]
    >;
    readonly withCtx: UnwrapRef<(typeof import("vue"))["withCtx"]>;
    readonly withDirectives: UnwrapRef<
      (typeof import("vue"))["withDirectives"]
    >;
    readonly withKeys: UnwrapRef<(typeof import("vue"))["withKeys"]>;
    readonly withMemo: UnwrapRef<(typeof import("vue"))["withMemo"]>;
    readonly withModifiers: UnwrapRef<(typeof import("vue"))["withModifiers"]>;
    readonly withScopeId: UnwrapRef<(typeof import("vue"))["withScopeId"]>;
  }
}
