// Generated by Nuxt'
import type { Plugin } from "#app";

type Decorate<T extends Record<string, any>> = {
  [K in keyof T as K extends string ? `$${K}` : never]: T[K];
};

type InjectionType<A extends Plugin> =
  A extends Plugin<infer T> ? Decorate<T> : unknown;

type NuxtAppInjections = InjectionType<
  typeof import("../../node_modules/nuxt/dist/app/plugins/revive-payload.server").default
> &
  InjectionType<
    typeof import("../../node_modules/nuxt/dist/app/plugins/revive-payload.client").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt/dist/head/runtime/plugins/unhead").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt/dist/pages/runtime/plugins/router").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt-unhead/dist/runtime/plugin").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt-schema-org/dist/runtime/plugin").default
  > &
  InjectionType<typeof import("../templates.pwa.client.6b3ab9aa").default> &
  InjectionType<
    typeof import("../../node_modules/nuxt-delay-hydration/dist/runtime/mount-plugin.client").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt-lazy-load/dist/runtime/plugin").default
  > &
  InjectionType<
    typeof import("../../node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default
  > &
  InjectionType<
    typeof import("../../node_modules/@nuxtjs/device/dist/runtime/plugin").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt-gtag/dist/runtime/plugin.client").default
  > &
  InjectionType<
    typeof import("../../node_modules/nuxt/dist/app/plugins/chunk-reload.client").default
  > &
  InjectionType<typeof import("../../plugins/vercel").default> &
  InjectionType<typeof import("../../plugins/markdownit").default> &
  InjectionType<typeof import("../../plugins/sanity-image-builder").default> &
  InjectionType<typeof import("../../plugins/vue-social-chat").default>;

declare module "#app" {
  interface NuxtApp extends NuxtAppInjections {}
}

declare module "vue" {
  interface ComponentCustomProperties extends NuxtAppInjections {}
}

export {};
