// generated by nuxt-seo-kit
import type { ModuleOptions } from "nuxt-seo-kit";
declare module "#nuxt-seo-kit/config" {
  export const splash: true | ModuleOptions["splash"];
  export const siteName:
    | "中國武術散打、功夫、自衛術（香港）"
    | ModuleOptions["siteName"];
  export const siteDescription:
    | "「香港極拳道武術協會」是香港政府及體育協會暨奧林匹克委員會認可及資助的體育總會「香港武術聯會」及「香港泰拳理事會」認可之屬會會員。本會推廣『散打自衛術』是香港政府認可及資助的武術運動項目之一。"
    | ModuleOptions["siteDescription"];
  export const siteImage: undefined | ModuleOptions["siteImage"];
  export const siteUrl: "https://hksanda.vercel.app" | ModuleOptions["siteUrl"];
  export const titleSeparator: "|" | ModuleOptions["titleSeparator"];
  export const trailingSlash: false | ModuleOptions["trailingSlash"];
  export const language: "zh-HK" | ModuleOptions["language"];
  export const indexable: false | ModuleOptions["indexable"];
}
