// Generated by nuxt-unhead

declare module "#app/nuxt" {
  import { HeadEntry, HeadTag } from "@vueuse/head";

  interface RuntimeNuxtHooks {
    "head:tags": (tag: HeadTag[]) => Promise<void> | void;
    "head:entries": (entries: HeadEntry[]) => Promise<void> | void;
  }
}

type PublicFiles =
  | "/favicon.ico"
  | "/googled0976c8b75e9e98f.html"
  | "/logo.png"
  | "/svg/close.svg"
  | "/svg/whatsapp.svg"
  | "/images/2QaciX.png"
  | "/images/blue-mountain.webp"
  | "/images/brush.png"
  | "/images/logo-58.png"
  | "/images/logo-71.png"
  | "/images/logo.png"
  | "/images/wood.jpeg"
  | (string & Record<never, never>);
type AssetFiles =
  | "~/css/tailwind.css"
  | "~/fonts/FZYanZQKSJF.TTF"
  | "~/fonts/luxun.otf"
  | "~/images/blue-mountain.webp"
  | "~/images/brush.png"
  | "~/images/logo-58.png"
  | "~/images/logo-71.png"
  | "~/images/logo.png"
  | "~/images/wood.jpeg"
  | "~/scss/bg_text.scss"
  | "~/scss/link.scss"
  | (string & Record<never, never>);

declare module "@nuxt/schema" {
  interface HeadAugmentations {
    link: {
      href: PublicFiles | AssetFiles;
    };
    script: {
      src: PublicFiles | AssetFiles;
    };
  }
}

// ensures we augment
export {};
