// Generated by nuxt-simple-sitemap
import type { SitemapItemDefaults } from "nuxt-simple-sitemap";

interface NuxtSimpleSitemapNitroRules {
  index?: boolean;
  sitemap?: SitemapItemDefaults;
}
declare module "nitropack" {
  interface NitroRouteRules extends NuxtSimpleSitemapNitroRules {}
  interface NitroRouteConfig extends NuxtSimpleSitemapNitroRules {}
}

export {};
